export const ERROR_VALIDATION = 'ERROR_VALIDATION'
export const TICKET_CREATE_SUCCESS = "TICKET_CREATE_SUCCESS"
export const TICKET_FETCH_SUCCESS = "TICKET_FETCH_SUCCESS"
export const TICKET_UPDATE_SUCCESS = "TICKET_UPDATE_SUCCESS"
export const TICKET_DELETE_SUCCESS = "TICKET_DELETE_SUCCESS"